# Generated by Django 4.2.16 on 2024-11-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reseñas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=200)),
                ('texto', models.TextField(max_length=1000)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
