# Generated by Django 4.2.18 on 2025-01-21 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='first_name',
            new_name='title',
        ),
    ]
