# Generated by Django 4.2.18 on 2025-01-21 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='email',
            new_name='email_adress',
        ),
        migrations.RemoveField(
            model_name='author',
            name='adress',
        ),
    ]
