# Generated by Django 4.2.19 on 2025-03-12 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0002_alter_student_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='degree',
            name='years',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
