# Generated by Django 4.2.18 on 2025-02-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_text',
        ),
        migrations.AddField(
            model_name='review',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='review',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='review',
            name='role',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='review',
            name='sign',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='review',
            name='web_server',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
